### ISSUE TITLE
Add test support for linux aarch64

### ISSUE THREAD

**Issue by odidev** [RonnyPfannschmidt/prance#128]
Hi Team, 

I tried testing **prance** package on **Arm64** architectures but it is genarating **10 deselected, 1 error** for` pytest -m "not requires_network"` command. The error seems to be **PyICU** package dependency. 

```
Collecting PyICU~=2.8.1  

Downloading PyICU-2.8.1.tar.gz (304 kB)  

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 304.2/304.2 KB 9.4 MB/s eta 0:00:00  

Installing build dependencies: started  

Installing build dependencies: finished with status 'done'  

Getting requirements to build wheel: started  

Getting requirements to build wheel: finished with status 'error'  

error: subprocess-exited-with-error  

 

Getting requirements to build wheel did not run successfully.  

│ exit code: 1  

╰─> [64 lines of output]  

(running 'icu-config --version')  

(running 'pkg-config --modversion icu-i18n')  

Traceback (most recent call last):  

File "setup.py", line 63, in <module>  

ICU_VERSION = os.environ['ICU_VERSION']  

File "/usr/lib/python3.8/os.py", line 675, in __getitem__  

raise KeyError(key) from None  

KeyError: 'ICU_VERSION'  

 

During handling of the above exception, another exception occurred:  

 

Traceback (most recent call last):  

File "setup.py", line 66, in <module>  

ICU_VERSION = check_output(('icu-config', '--version')).strip()  

File "setup.py", line 19, in check_output  

return subprocess_check_output(popenargs)  

File "/usr/lib/python3.8/subprocess.py", line 415, in check_output  

return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,  

File "/usr/lib/python3.8/subprocess.py", line 493, in run  

with Popen(*popenargs, **kwargs) as process:  

File "/usr/lib/python3.8/subprocess.py", line 858, in __init__  

self._execute_child(args, executable, preexec_fn, close_fds,  

File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child  

raise child_exception_type(errno_num, err_msg, err_filename)  

FileNotFoundError: [Errno 2] No such file or directory: 'icu-config'  

 

During handling of the above exception, another exception occurred:  

 

Traceback (most recent call last):  

File "setup.py", line 69, in <module>  

ICU_VERSION = check_output(('pkg-config', '--modversion', 'icu-i18n')).strip()  

File "setup.py", line 19, in check_output  

return subprocess_check_output(popenargs)  

File "/usr/lib/python3.8/subprocess.py", line 415, in check_output  

return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,  

File "/usr/lib/python3.8/subprocess.py", line 493, in run  

with Popen(*popenargs, **kwargs) as process:  

File "/usr/lib/python3.8/subprocess.py", line 858, in __init__  

self._execute_child(args, executable, preexec_fn, close_fds,  

File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child  

raise child_exception_type(errno_num, err_msg, err_filename)  

FileNotFoundError: [Errno 2] No such file or directory: 'pkg-config'  

 

During handling of the above exception, another exception occurred:  

 

Traceback (most recent call last):  

File "/ws/py38-venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>  

main()  

File "/ws/py38-venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main  

json_out['return_val'] = hook(**hook_input['kwargs'])  

File "/ws/py38-venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel  

return hook(config_settings)  

File "/tmp/pip-build-env-svy8jxp7/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 161, in get_requires_for_build_wheel  

return self._get_build_requires(  

File "/tmp/pip-build-env-svy8jxp7/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 142, in _get_build_requires  

self.run_setup()  

File "/tmp/pip-build-env-svy8jxp7/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 157, in run_setup  

exec(compile(code, __file__, 'exec'), locals())  

File "setup.py", line 71, in <module>  

raise RuntimeError('''  

RuntimeError:  

Please install pkg-config on your system or set the ICU_VERSION environment  

variable to the version of ICU you have installed.  

  

[end of output]  

  

note: This error originates from a subprocess, and is likely not a problem with pip.  

error: subprocess-exited-with-error  

  

 Getting requirements to build wheel did not run successfully.  

│ exit code: 1  

╰─> See above for output.  

note: This error originates from a subprocess, and is likely not a problem with pip.  

Error: Process completed with exit code 1.  

```
I checked the **PyICU** support and installed through [PyICU · PyPI.](https://pypi.org/project/PyICU/#modal-close) which got successful but doesn't solve the issue. Also PyICU is an **archived** repository. 

**GHA_test logs for Arm64:** https://github.com/odidev/prance/runs/5198811181?check_suite_focus=true  

Could you please share your feedback regarding this and suggest what can be done to test it over ARM64 server? 

Thanks in advance.

**Comment by RonnyPfannschmidt** [comment]
icu itself is optional, and as far as i can tell it need build time dependencies

i would recommend jsut leaving it out, it may make sense to patch it out alltogether these days
